version: '3.8'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - nextjs

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    depends_on:
      mysql:
        condition: service_started
    ports:
      - '3000:3000'
    expose:
      - '3000'
    restart: always

  prisma_studio:
    depends_on:
      mysql:
        condition: service_started
    container_name: prisma_studio
    ports:
      - '5555:5555'
    build:
      context: ./prisma
      dockerfile: Dockerfile

  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - nextjsApp-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=wl69trG7FzwzoyxfQTmxjsqF046KEPmi
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=wl69trG7FzwzoyxfQTmxjsqF046KEPmi 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
    restart: always
    expose:
      - '3306'
volumes:
  nextjsApp-mysql-data:
