GET http://localhost:3000/user/loggedInUser
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiSmFuY3kiLCJsYXN0TmFtZSI6IkNhcGVsbGFuIiwibWlkZGxlTmFtZSI6IiIsInBhc3N3b3JkIjoiMTIzIiwiZW1haWwiOiJqYW5jeWNhcGVsbGFuOTdAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiY29tcGFueSI6bnVsbCwiYnJhbmNoTmFtZSI6bnVsbCwibGFzdFNhbGVEYXRlIjpudWxsLCJsYXN0TG9naW4iOm51bGwsInByZWZlcnJlZExhbmd1YWdlIjoiRW5nbGlzaCIsImxpY2Vuc2VJZCI6bnVsbCwiaWF0IjoxNjM1MzAyODM5LCJleHAiOjE2MzUzMDY0Mzl9.-9KksOc7S2BwP7WMEEBuPgu-WcS3wx-ipeBYTsaJ4UM

### 

POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "jancycapellan97@gmail.com",
  "password": "123"
}