name: CD

on:
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.18.1'
      - run: npm ci
      - run: npm run build
      
